/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace SMS2FlowMachineRegistry {
  export type MachineStruct = {
    machineId: BigNumberish;
    owner: AddressLike;
    machineCode: string;
    location: string;
    active: boolean;
    totalRevenue: BigNumberish;
  };

  export type MachineStructOutput = [
    machineId: bigint,
    owner: string,
    machineCode: string,
    location: string,
    active: boolean,
    totalRevenue: bigint
  ] & {
    machineId: bigint;
    owner: string;
    machineCode: string;
    location: string;
    active: boolean;
    totalRevenue: bigint;
  };

  export type ProductStruct = {
    productId: BigNumberish;
    machineId: BigNumberish;
    sku: string;
    name: string;
    priceWei: BigNumberish;
    stock: BigNumberish;
    active: boolean;
  };

  export type ProductStructOutput = [
    productId: bigint,
    machineId: bigint,
    sku: string,
    name: string,
    priceWei: bigint,
    stock: bigint,
    active: boolean
  ] & {
    productId: bigint;
    machineId: bigint;
    sku: string;
    name: string;
    priceWei: bigint;
    stock: bigint;
    active: boolean;
  };

  export type PurchaseStruct = {
    purchaseId: BigNumberish;
    machineId: BigNumberish;
    productId: BigNumberish;
    buyer: AddressLike;
    amountPaid: BigNumberish;
    smsReference: string;
    dispensed: boolean;
    refunded: boolean;
    createdAt: BigNumberish;
  };

  export type PurchaseStructOutput = [
    purchaseId: bigint,
    machineId: bigint,
    productId: bigint,
    buyer: string,
    amountPaid: bigint,
    smsReference: string,
    dispensed: boolean,
    refunded: boolean,
    createdAt: bigint
  ] & {
    purchaseId: bigint;
    machineId: bigint;
    productId: bigint;
    buyer: string;
    amountPaid: bigint;
    smsReference: string;
    dispensed: boolean;
    refunded: boolean;
    createdAt: bigint;
  };
}

export interface SMS2FlowMachineRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "OPERATOR_ROLE"
      | "addProduct"
      | "confirmDispense"
      | "getMachine"
      | "getMachineRevenue"
      | "getProduct"
      | "getProductsByMachine"
      | "getPurchase"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "purchaseProduct"
      | "refundPurchase"
      | "registerMachine"
      | "renounceRole"
      | "revokeRole"
      | "supportsInterface"
      | "updateMachineStatus"
      | "updateProduct"
      | "withdrawMachineRevenue"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DispenseConfirmed"
      | "MachineRegistered"
      | "MachineStatusUpdated"
      | "ProductAdded"
      | "ProductPurchased"
      | "ProductUpdated"
      | "PurchaseRefunded"
      | "RevenueWithdrawn"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OPERATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addProduct",
    values: [BigNumberish, string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmDispense",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMachine",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMachineRevenue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProduct",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProductsByMachine",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPurchase",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "purchaseProduct",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "refundPurchase",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerMachine",
    values: [string, string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMachineStatus",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProduct",
    values: [BigNumberish, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawMachineRevenue",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "OPERATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addProduct", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confirmDispense",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMachine", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMachineRevenue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getProduct", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getProductsByMachine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPurchase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "purchaseProduct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "refundPurchase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerMachine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMachineStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProduct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawMachineRevenue",
    data: BytesLike
  ): Result;
}

export namespace DispenseConfirmedEvent {
  export type InputTuple = [purchaseId: BigNumberish, confirmedBy: AddressLike];
  export type OutputTuple = [purchaseId: bigint, confirmedBy: string];
  export interface OutputObject {
    purchaseId: bigint;
    confirmedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MachineRegisteredEvent {
  export type InputTuple = [
    machineId: BigNumberish,
    owner: AddressLike,
    machineCode: string,
    location: string
  ];
  export type OutputTuple = [
    machineId: bigint,
    owner: string,
    machineCode: string,
    location: string
  ];
  export interface OutputObject {
    machineId: bigint;
    owner: string;
    machineCode: string;
    location: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MachineStatusUpdatedEvent {
  export type InputTuple = [machineId: BigNumberish, active: boolean];
  export type OutputTuple = [machineId: bigint, active: boolean];
  export interface OutputObject {
    machineId: bigint;
    active: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProductAddedEvent {
  export type InputTuple = [
    productId: BigNumberish,
    machineId: BigNumberish,
    sku: string,
    name: string,
    priceWei: BigNumberish,
    stock: BigNumberish
  ];
  export type OutputTuple = [
    productId: bigint,
    machineId: bigint,
    sku: string,
    name: string,
    priceWei: bigint,
    stock: bigint
  ];
  export interface OutputObject {
    productId: bigint;
    machineId: bigint;
    sku: string;
    name: string;
    priceWei: bigint;
    stock: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProductPurchasedEvent {
  export type InputTuple = [
    purchaseId: BigNumberish,
    machineId: BigNumberish,
    productId: BigNumberish,
    buyer: AddressLike,
    amountPaid: BigNumberish,
    smsReference: string
  ];
  export type OutputTuple = [
    purchaseId: bigint,
    machineId: bigint,
    productId: bigint,
    buyer: string,
    amountPaid: bigint,
    smsReference: string
  ];
  export interface OutputObject {
    purchaseId: bigint;
    machineId: bigint;
    productId: bigint;
    buyer: string;
    amountPaid: bigint;
    smsReference: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProductUpdatedEvent {
  export type InputTuple = [
    productId: BigNumberish,
    priceWei: BigNumberish,
    stock: BigNumberish,
    active: boolean
  ];
  export type OutputTuple = [
    productId: bigint,
    priceWei: bigint,
    stock: bigint,
    active: boolean
  ];
  export interface OutputObject {
    productId: bigint;
    priceWei: bigint;
    stock: bigint;
    active: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PurchaseRefundedEvent {
  export type InputTuple = [
    purchaseId: BigNumberish,
    buyer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [purchaseId: bigint, buyer: string, amount: bigint];
  export interface OutputObject {
    purchaseId: bigint;
    buyer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RevenueWithdrawnEvent {
  export type InputTuple = [
    machineId: BigNumberish,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [machineId: bigint, to: string, amount: bigint];
  export interface OutputObject {
    machineId: bigint;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SMS2FlowMachineRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): SMS2FlowMachineRegistry;
  waitForDeployment(): Promise<this>;

  interface: SMS2FlowMachineRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  OPERATOR_ROLE: TypedContractMethod<[], [string], "view">;

  addProduct: TypedContractMethod<
    [
      machineId: BigNumberish,
      sku: string,
      name: string,
      priceWei: BigNumberish,
      stock: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  confirmDispense: TypedContractMethod<
    [purchaseId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getMachine: TypedContractMethod<
    [machineId: BigNumberish],
    [SMS2FlowMachineRegistry.MachineStructOutput],
    "view"
  >;

  getMachineRevenue: TypedContractMethod<
    [machineId: BigNumberish],
    [bigint],
    "view"
  >;

  getProduct: TypedContractMethod<
    [productId: BigNumberish],
    [SMS2FlowMachineRegistry.ProductStructOutput],
    "view"
  >;

  getProductsByMachine: TypedContractMethod<
    [machineId: BigNumberish],
    [bigint[]],
    "view"
  >;

  getPurchase: TypedContractMethod<
    [purchaseId: BigNumberish],
    [SMS2FlowMachineRegistry.PurchaseStructOutput],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  purchaseProduct: TypedContractMethod<
    [machineId: BigNumberish, productId: BigNumberish, smsReference: string],
    [bigint],
    "payable"
  >;

  refundPurchase: TypedContractMethod<
    [purchaseId: BigNumberish],
    [void],
    "nonpayable"
  >;

  registerMachine: TypedContractMethod<
    [machineCode: string, location: string, machineOwner: AddressLike],
    [bigint],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  updateMachineStatus: TypedContractMethod<
    [machineId: BigNumberish, active: boolean],
    [void],
    "nonpayable"
  >;

  updateProduct: TypedContractMethod<
    [
      productId: BigNumberish,
      priceWei: BigNumberish,
      stock: BigNumberish,
      active: boolean
    ],
    [void],
    "nonpayable"
  >;

  withdrawMachineRevenue: TypedContractMethod<
    [machineId: BigNumberish, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "OPERATOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addProduct"
  ): TypedContractMethod<
    [
      machineId: BigNumberish,
      sku: string,
      name: string,
      priceWei: BigNumberish,
      stock: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confirmDispense"
  ): TypedContractMethod<[purchaseId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getMachine"
  ): TypedContractMethod<
    [machineId: BigNumberish],
    [SMS2FlowMachineRegistry.MachineStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMachineRevenue"
  ): TypedContractMethod<[machineId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getProduct"
  ): TypedContractMethod<
    [productId: BigNumberish],
    [SMS2FlowMachineRegistry.ProductStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProductsByMachine"
  ): TypedContractMethod<[machineId: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getPurchase"
  ): TypedContractMethod<
    [purchaseId: BigNumberish],
    [SMS2FlowMachineRegistry.PurchaseStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "purchaseProduct"
  ): TypedContractMethod<
    [machineId: BigNumberish, productId: BigNumberish, smsReference: string],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "refundPurchase"
  ): TypedContractMethod<[purchaseId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerMachine"
  ): TypedContractMethod<
    [machineCode: string, location: string, machineOwner: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "updateMachineStatus"
  ): TypedContractMethod<
    [machineId: BigNumberish, active: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateProduct"
  ): TypedContractMethod<
    [
      productId: BigNumberish,
      priceWei: BigNumberish,
      stock: BigNumberish,
      active: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawMachineRevenue"
  ): TypedContractMethod<
    [machineId: BigNumberish, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DispenseConfirmed"
  ): TypedContractEvent<
    DispenseConfirmedEvent.InputTuple,
    DispenseConfirmedEvent.OutputTuple,
    DispenseConfirmedEvent.OutputObject
  >;
  getEvent(
    key: "MachineRegistered"
  ): TypedContractEvent<
    MachineRegisteredEvent.InputTuple,
    MachineRegisteredEvent.OutputTuple,
    MachineRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "MachineStatusUpdated"
  ): TypedContractEvent<
    MachineStatusUpdatedEvent.InputTuple,
    MachineStatusUpdatedEvent.OutputTuple,
    MachineStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ProductAdded"
  ): TypedContractEvent<
    ProductAddedEvent.InputTuple,
    ProductAddedEvent.OutputTuple,
    ProductAddedEvent.OutputObject
  >;
  getEvent(
    key: "ProductPurchased"
  ): TypedContractEvent<
    ProductPurchasedEvent.InputTuple,
    ProductPurchasedEvent.OutputTuple,
    ProductPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "ProductUpdated"
  ): TypedContractEvent<
    ProductUpdatedEvent.InputTuple,
    ProductUpdatedEvent.OutputTuple,
    ProductUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PurchaseRefunded"
  ): TypedContractEvent<
    PurchaseRefundedEvent.InputTuple,
    PurchaseRefundedEvent.OutputTuple,
    PurchaseRefundedEvent.OutputObject
  >;
  getEvent(
    key: "RevenueWithdrawn"
  ): TypedContractEvent<
    RevenueWithdrawnEvent.InputTuple,
    RevenueWithdrawnEvent.OutputTuple,
    RevenueWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;

  filters: {
    "DispenseConfirmed(uint256,address)": TypedContractEvent<
      DispenseConfirmedEvent.InputTuple,
      DispenseConfirmedEvent.OutputTuple,
      DispenseConfirmedEvent.OutputObject
    >;
    DispenseConfirmed: TypedContractEvent<
      DispenseConfirmedEvent.InputTuple,
      DispenseConfirmedEvent.OutputTuple,
      DispenseConfirmedEvent.OutputObject
    >;

    "MachineRegistered(uint256,address,string,string)": TypedContractEvent<
      MachineRegisteredEvent.InputTuple,
      MachineRegisteredEvent.OutputTuple,
      MachineRegisteredEvent.OutputObject
    >;
    MachineRegistered: TypedContractEvent<
      MachineRegisteredEvent.InputTuple,
      MachineRegisteredEvent.OutputTuple,
      MachineRegisteredEvent.OutputObject
    >;

    "MachineStatusUpdated(uint256,bool)": TypedContractEvent<
      MachineStatusUpdatedEvent.InputTuple,
      MachineStatusUpdatedEvent.OutputTuple,
      MachineStatusUpdatedEvent.OutputObject
    >;
    MachineStatusUpdated: TypedContractEvent<
      MachineStatusUpdatedEvent.InputTuple,
      MachineStatusUpdatedEvent.OutputTuple,
      MachineStatusUpdatedEvent.OutputObject
    >;

    "ProductAdded(uint256,uint256,string,string,uint256,uint256)": TypedContractEvent<
      ProductAddedEvent.InputTuple,
      ProductAddedEvent.OutputTuple,
      ProductAddedEvent.OutputObject
    >;
    ProductAdded: TypedContractEvent<
      ProductAddedEvent.InputTuple,
      ProductAddedEvent.OutputTuple,
      ProductAddedEvent.OutputObject
    >;

    "ProductPurchased(uint256,uint256,uint256,address,uint256,string)": TypedContractEvent<
      ProductPurchasedEvent.InputTuple,
      ProductPurchasedEvent.OutputTuple,
      ProductPurchasedEvent.OutputObject
    >;
    ProductPurchased: TypedContractEvent<
      ProductPurchasedEvent.InputTuple,
      ProductPurchasedEvent.OutputTuple,
      ProductPurchasedEvent.OutputObject
    >;

    "ProductUpdated(uint256,uint256,uint256,bool)": TypedContractEvent<
      ProductUpdatedEvent.InputTuple,
      ProductUpdatedEvent.OutputTuple,
      ProductUpdatedEvent.OutputObject
    >;
    ProductUpdated: TypedContractEvent<
      ProductUpdatedEvent.InputTuple,
      ProductUpdatedEvent.OutputTuple,
      ProductUpdatedEvent.OutputObject
    >;

    "PurchaseRefunded(uint256,address,uint256)": TypedContractEvent<
      PurchaseRefundedEvent.InputTuple,
      PurchaseRefundedEvent.OutputTuple,
      PurchaseRefundedEvent.OutputObject
    >;
    PurchaseRefunded: TypedContractEvent<
      PurchaseRefundedEvent.InputTuple,
      PurchaseRefundedEvent.OutputTuple,
      PurchaseRefundedEvent.OutputObject
    >;

    "RevenueWithdrawn(uint256,address,uint256)": TypedContractEvent<
      RevenueWithdrawnEvent.InputTuple,
      RevenueWithdrawnEvent.OutputTuple,
      RevenueWithdrawnEvent.OutputObject
    >;
    RevenueWithdrawn: TypedContractEvent<
      RevenueWithdrawnEvent.InputTuple,
      RevenueWithdrawnEvent.OutputTuple,
      RevenueWithdrawnEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
  };
}
